### ISSUE TITLE
RTX Remix issue

### ISSUE THREAD

**Issue by KingVulpes** [cdozdil/OptiScaler#10]
When trying to run OptiScaler in Portal RTX on my Steam Deck, I get a Computed DLSS Mode: invalid, Render Resolution: 0x0 error and no upscaling is done

**Comment by cdozdil** [comment]
Could you edit nvngx.ini file and set LogToFile=true and LogLevel=0, after this please run game again. It will create a file called OptiScaler.log. Please share this file here.

**Comment by KingVulpes** [comment]
> Could you edit nvngx.ini file and set LogToFile=true and LogLevel=0, after this please run game again. It will create a file called OptiScaler.log. Please share this file here.

[OptiScaler.log](https://github.com/user-attachments/files/16007132/OptiScaler.log)

**Comment by cdozdil** [comment]
As far as I undertsand from this logs Portal RTX does not create DLSS feature. Also checks for frame generation support
```
GetT('FrameGeneration.Available', FAIL)
```
Will try on my side and give more info

**Comment by KingVulpes** [comment]
> As far as I undertsand from this logs Portal RTX does not create DLSS feature. Also checks for frame generation support
> 
> ```
> GetT('FrameGeneration.Available', FAIL)
> ```
> 
> Will try on my side and give more info

Alr, thanks 👍

**Comment by cdozdil** [comment]
Hi there, have you checked [this](https://github.com/cdozdil/OptiScaler/releases/tag/v0.6.5-pre6) release?

**Comment by KingVulpes** [comment]
> Hi there, have you checked [this](https://github.com/cdozdil/OptiScaler/releases/tag/v0.6.5-pre6) release?

I have and it helped very much 👍

**Comment by arronieo** [comment]
I am experiencing this exact issue, even with the latest release

**Comment by cdozdil** [comment]
Hi,

Have you installed as [non-nvngx](https://github.com/cdozdil/OptiScaler#install-as-non-nvngx) ? Also you need to set `VulkanExtensionSpoofing=true` and `Vulkan=true` from `nvngx.ini`

**Comment by arronieo** [comment]
I have tried, however there is no nvngx_dlss.dll only nvngx_dlssg.dll and nvngx_dlssd.dll and neither of them work with the method

**Comment by cdozdil** [comment]
I think you have an issue with your installation. For sure these should be a nvngx_dlss.dll file. Could you verify your files from Steam?

**Comment by arronieo** [comment]
i have verified and was able to get nvngx_dlss.dll. and i have followed the steps to install as non nvngx. starting the game with this installed this way causes my graphics driver to time out
