### ISSUE TITLE
0.6.1 strange behaviour with MipmapBiasOverride

### ISSUE THREAD

**Issue by donizettilorenzo** [cdozdil/OptiScaler#11]
Horizon Zero Dawn, DLSS

I can set the MipmapBiasOverride to the correct value - through the "calculate" form - but applying it make the game crash after some time (changing the resolution or restarting the game)

**Comment by cdozdil** [comment]
Hi, 

I have replicated behaovior on my end and I believe solved it. 

Could you test this build if it's still crashing?
[OptiScaler.v0.6.2-pre4.zip](https://github.com/user-attachments/files/16071524/OptiScaler.v0.6.2-pre4.zip)

**Comment by donizettilorenzo** [comment]
it works!
