### ISSUE TITLE
Dynamic frame generation is mislabeled

### ISSUE THREAD

**Issue by krillme** [cdozdil/OptiScaler#112]
The dynamic frame generation option in OptiScaler is mislabeled, or perhaps isn't functioning properly. The description reads "enables FG only when FPS would go below FPS limit". This appears to be incorrect. What this option is really doing is changing how your FPS limit is interpreted. When "dynamic frame generation" is disabled, setting the FPS limit to 60 FPS will run the application at 30 FPS with frame generation enabled. However if "dynamic frame generation" is enabled, the application will run at 60 FPS with frame generation enabled up to 120 FPS. Essentially, disabling DFG interprets the FPS limit as your post-FG result, while enabling DFG interprets the FPS limit as the pre-FG result.

**Comment by cdozdil** [comment]
Hi,

I am using names as described at `DLSS Enabler` ini & docs. You might suggest this change at [Nexus](https://www.nexusmods.com/site/mods/757) to Artur.
