### ISSUE TITLE
New FSR3 versions

### ISSUE THREAD

**Issue by xHybred** [cdozdil/OptiScaler#121]
I've been using this version of FSR3 for awhile now, I noticed your mod's version is outdated. Here's the link: https://www.mediafire.com/folder/q9qtznpw6q1jg/FSR+Latest+|+3.1+

I keep all DLLs updated including developer previews here: https://www.mediafire.com/folder/ajsk8k2n4aq2u/GPU+DLLs

Version: 1.0.2.37812

**Comment by cdozdil** [comment]
Hi,

Ones in the mod are from GpuOpen repo compiled with the fixes I have added to them. You can check my fork for changes.
