### ISSUE TITLE
Implement Snapdragon GSR 2

### ISSUE THREAD

**Issue by ninele7** [cdozdil/OptiScaler#122]
https://github.com/SnapdragonStudios/snapdragon-gsr/tree/main/sgsr/v2

Snapdragon GSR 2 is temporal upscaler optimized for weak hardware with low memory bandwidth. It might be valuable for handhelds and laptops. Also it might be especially valuable for ARM based Windows devices. 

As far as I understand it requires same inputs as FSR and has 3 implementation. 2 of them use compute shaders and fastest one uses fragment shaders.

How hard would it be to implement it into OptiScaler?

**Comment by cdozdil** [comment]
Hi,

Afaik it's a fork of FSR2 and currently does not have a API/Framework for resource management etc. Results from it's own demo is not so bright too, so I don't wanna spend energy on it now. If they provide proper API/Framework and documentation I might check.
