### ISSUE TITLE
Crash on resolution change/exit full screen

### ISSUE THREAD

**Issue by SparxySys** [cdozdil/OptiScaler#13]
I'm running Final Fantasy XIV (under linux/proton) and seeing a crash when I exit full screen borderless (i.e. changing window size/resolution I guess?)
This occurs with optiscaler 0.6.1 as well as 0.6.5-pre3. 

I'm using FSR 2.2.

```
Dx11Upscaler=fsr22
```

Not sure if this is fixable on optiscaler's end, if there's any way I can provide more useful info please let me know.

**Comment by SparxySys** [comment]
Log file at loglevel 0 
[OptiScaler.tar.gz](https://github.com/user-attachments/files/16176399/OptiScaler.tar.gz)

**Comment by cdozdil** [comment]
Hi there,

I think game is calling evaluate with null FeatureId, could you test this build if it solves your issue?

[nvngx.zip](https://github.com/user-attachments/files/16177357/nvngx.zip)

**Comment by SparxySys** [comment]
Thank you @cdozdil, it looks like that was the issue! Resizing the game window works fine with that build :+1:
