### ISSUE TITLE
v0.7.0 runs normally but no frame generation menu

### ISSUE THREAD

**Issue by Loong111** [cdozdil/OptiScaler#131]
I tried using OptiScaler in Baldur's Gate 3, and the menu runs normally and displays fsr3.1.2, but as shown in the following figure, the frame generation menu does not appear.
![6bd77ffabdd64c37c947ef905e8a91be](https://github.com/user-attachments/assets/2e88ed6e-0e76-4467-99bb-150944dba2f6)
[OptiScaler.log](https://github.com/user-attachments/files/17978595/OptiScaler.log)

**Comment by cdozdil** [comment]
Yes, FG is only for Dx12 for now

**Comment by Loong111** [comment]
> Yes, FG is only for Dx12 for now

Thank you, but I have another question, when I run SM2, installing optiscaler causes the game to crash on startup, EAC has been disabled.

[OptiScaler.log](https://github.com/user-attachments/files/17979711/OptiScaler.log)

**Comment by 4evrplan** [comment]
> Yes, FG is only for Dx12 for now

I came here to say the same thing (no FG menu) about God of War (2022 port - _not_ Ragnarok). Is the hope to eventually allow FG in DX11 through AFMF? That would be amazing! I'm currently using Lossless Scaling, but there is a lot of visual artifacting in LS, since it doesn't have access to motion vectors (nor I assume to the depth buffer or a HUD mask).

**Comment by cdozdil** [comment]
Hi,

There is no XeSS 2.0 SDK yet, when Intel release it will check. From initial testings I can say
* Dx11 support it Arc only
* Vulkan support is ok on most modern GPUs
* FG will be Arc only  

If you have an Arc card and test there are test builds for it at Discord channel.

**Comment by cdozdil** [comment]
> > Yes, FG is only for Dx12 for now
> 
> Thank you, but I have another question, when I run SM2, installing optiscaler causes the game to crash on startup, EAC has been disabled.
> 
> [OptiScaler.log](https://github.com/user-attachments/files/17979711/OptiScaler.log)

I think with latest patch SM2 have brake something but you should not need Opti anymore, they added FG afaik.
