### ISSUE TITLE
FSR Frame gen in vulkan games?

### ISSUE THREAD

**Issue by dagger0065** [cdozdil/OptiScaler#138]
Hi, is there a way to activate frame gen in vulkan api based games, e.g., Indiana Jones and the great circle? 
Game runs smoothly anyways, but would appreciate the extra FPS boost from frame gen.

**Comment by iKillThis** [comment]
Did you find a way to activate it in Indiana Jones without crashing ?

**Comment by cdozdil** [comment]
Currently I don't have any plans for Vulkan FG

**Comment by Ap3xY** [comment]
Hi, I saw that this was mentioned and would like to know if anything has changed regarding the implementation of Vulkan FG. I started playing X4: Foundations and thought that FG would be a fantastic addition but the game runs on Vulkan and has no plans to implement DX12.
