### ISSUE TITLE
FSR 3.1 on Cyberpunk 2077 doesn't seem to work! Menu showed only FSR 2.1 and 2.2, enabling 3.1 via nvngx.ini results in a game crash upon launch.

### ISSUE THREAD

**Issue by Lighwan** [cdozdil/OptiScaler#14]
Am I misunderstanding something? I am on the newest release version with fsr 3.1 support, and 3.1 is mentioned in the .ini file.

**Comment by cdozdil** [comment]
Hi,

Try this pre-release build:
https://github.com/cdozdil/OptiScaler/releases/tag/v0.6.5-pre3

**Comment by Lighwan** [comment]
I believe that is the version I used. I will try pre4 now though

**Comment by Lighwan** [comment]
![image](https://github.com/user-attachments/assets/b325e058-06ee-4924-b0c2-f7e806b43688)
Still no fsr3 option unfortunately on version pre3 or pre4

**Comment by cdozdil** [comment]
Please check the in-game menu title bar. It says 0.6.1-final.

**Comment by Lighwan** [comment]
![image](https://github.com/user-attachments/assets/2e016c84-a1b9-4ece-a009-04122aa2a3a8)
These are the two versions i installed and extracted into the folder with the .exe. I'm not quite sure why it is saying that? Are the files on github of the wrong branch? Is it falling back to a previous version for some reason? I haven't interacted with version 0.6.1 in any manner.

**Comment by cdozdil** [comment]
I just noticed that you have DLSS Enabler installed. DLSS Enabler already have OptiScaler bundeled as `dlss-enabler-upscaler.dll`. To update OptiScaler when using DLSS Enabler:  
1. Delete/rename `dlss-enabler-upscaler.dll` in game folder
2. Copy `nvngx.dll` file from 7zip to game folder
3. Rename `nvngx.dll` to `dlss-enabler-upscaler.dll`

Ah also don't forget to copy `amd_fidelityfx_dx12.dll` file from 7zip file for FSR3.1.

**Comment by Lighwan** [comment]
Thank you! That worked. Didn't realize dlss enabler had Optiscaler included. Great support
