### ISSUE TITLE
Baldurs Gate 3 FG option not showing

### ISSUE THREAD

**Issue by zeidyy** [cdozdil/OptiScaler#141]
So, i installed directly as in instructions and yes mod is working but frame generation option are nowhere to be seen
Mod version is: [v0.7.0-pre66], and i installed it as  non-nvngx
Game running on DirectX11
Im using GTX1050 TI
![photo_5397910152130194398_w](https://github.com/user-attachments/assets/56b7f1e4-47f5-4525-aeed-b73b983cc80d)

**Comment by Vargach** [comment]
I have the same problem with Alan Wake 2. The frame generation section did not appear. But the game does not start if you install it according to the instructions, namely if you rename the optiscaler file nvngx.dll to dxgi.dll or another of the suggested names. That is, the game starts if you do not copy the nvngx_dlss.dll file and do not change the optiscaler file nvngx.dll

**Comment by quuinnn** [comment]
https://github.com/cdozdil/OptiScaler/issues/131#issuecomment-2511674002

Frame Generation is DX12 only. BG3 only supports Vulkan and DX11.
