### ISSUE TITLE
FSR3.1 crashing on Doom Eternal (Linux)

### ISSUE THREAD

**Issue by DrBob2** [cdozdil/OptiScaler#15]
Version v0.6.5-pre4 - Running on SteamDeck
Trying to switch to FSR3.1 on Doom Eternal crashes the game, FSR2.1/2.2 work fine, using the winmm.dll (WineDLL override) via [https://www.nexusmods.com/doometernal/mods/1170?tab=files](url)

Changing the INI so it starts on boot causes the same crash, happy to provide more logs as needed!

Log switching between FSR2.2 to FSR3.1 via GUI
[OptiScaler.log](https://github.com/user-attachments/files/16200717/OptiScaler.log)
Fresh log launching with FSR3.1
[OptiScaler2.log](https://github.com/user-attachments/files/16200733/OptiScaler2.log)
Fresh log switching from 2.1 to 3.1 - Set to LogLevel=0
[OptiScalerloglevel0.log](https://github.com/user-attachments/files/16200769/OptiScalerloglevel0.log)

Thanks!

**Comment by cdozdil** [comment]
Hi, 

Sorry for late reply, Vulkan side of stuff a bit rough. I specially build Vulkan FSR3.1 dll to make Doom Eternal work (but tested on Windows). I have a few more reports about Vulkan & FSR3.1. Hopefully will try to find a solution.

**Comment by cdozdil** [comment]
Hi again,

Today after a debug session we have fixed a crash on RDR2 Vulkan. Could you try thid build if it helps you too?  

[amd_fidelityfx_vk.zip](https://github.com/user-attachments/files/16228092/amd_fidelityfx_vk.zip)

**Comment by DrBob2** [comment]
Appreciate the update, early days for the 3.1 implantation particularly for Vulkan! A Plagues Tale: Requiem with the DX12 FSR3.1 works on the deck as an example.

I've tried again, and although it doesn't crash the game on swap, it freezes the game up once swapped (music still plays etc),  if I launch with FSR3.1 via INI it'll load the game until the main menu then black screen.

Swapping from 2.1 to 3.1 in main menu
[OptiScalerFSR21 to FSR31 new VK.log](https://github.com/user-attachments/files/16229588/OptiScalerFSR21.to.FSR31.new.VK.log)

FSR3.1 set via INI, game loads until main menu
[OptiScaler FSR31 INI.log](https://github.com/user-attachments/files/16229589/OptiScaler.FSR31.INI.log)

Pic of it swapping from 2.1 to 3.1 prior to freeze.
![Doom FSR3 1 Switch](https://github.com/user-attachments/assets/3482b129-0524-41e4-85c1-a4ca899e0598)

**Comment by cdozdil** [comment]
Hi,

According to logs it's "upscaling". On Windows I don't have this issue too. 
I can think of 2 possible outcomes:
1. Your GPU does not support Vulkan level 1.1 (very unlikely)
2. Some driver & extensions incompability issue at FSR3.1 side.

**Comment by cdozdil** [comment]
Hi,

Could you check with latest version of Doom Eternal. I have a report that it works with latest rev3 update. You need to install OptiScaler as [non-nvngx](https://github.com/cdozdil/OptiScaler#install-as-non-nvngx) and set `Vulkan=true` and  `VulkanExtensionSpoofing=true` under `[Spoofing]` section of `nvngx.ini`

**Comment by DrBob2** [comment]
Tested and FSR3.1 is working. Noice
