### ISSUE TITLE
teste dragons dogma 2 for amd

### ISSUE THREAD

**Issue by VelasquezZZ12** [cdozdil/OptiScaler#20]
Is it possible to use it in Dragon Dogma 2?
If you could have a way to explain it I would be grateful!

**Comment by cdozdil** [comment]
Hi,

Last time when I have tried DD2 most critical part in `nvngx.ini` were

```ini
; Skips upscaling of n frames
; n is integer number  - Default (auto) is disabled
SkipFirstFrames=15

; Restore last used compute signature after upscaling
; true or false - Default (auto) is false
RestoreComputeSignature=true
```

these settings. Most probably you wound need [reframework](https://github.com/praydog/REFramework/releases) 

Also in general DD2 is really picky/fragile game. For example I can't get Arc & Opti working with DD2

**Comment by VelasquezZZ12** [comment]
> Oi,
> 
> Da última vez que tentei o DD2, a parte mais crítica `nvngx.ini`foi
> 
> ```ini
> ; Skips upscaling of n frames
> ; n is integer number  - Default (auto) is disabled
> SkipFirstFrames=15
> 
> ; Restore last used compute signature after upscaling
> ; true or false - Default (auto) is false
> RestoreComputeSignature=true
> ```
> 
> essas configurações. Provavelmente você precisará [reformular](https://github.com/praydog/REFramework/releases)
> 
> Não me lembro, mas se o jogo for atualizado para DLSS 3.7, é melhor usar [o método dxgi.dll](https://github.com/cdozdil/OptiScaler?tab=readme-ov-file#installation-for-dlss-37-and-above-as-non-nvngx)
> 
> Também em geral DD2 é um jogo muito exigente/frágil. Por exemplo, não consigo fazer Arc e Opti funcionarem com DD2
I did the test here and it worked correctly, thank you very much for the incredible work

**Comment by VelasquezZZ12** [comment]
I did the test here and it worked correctly, thank you very much for the incredible work
