### ISSUE TITLE
Menu not popping up

### ISSUE THREAD

**Issue by MaxMo20** [cdozdil/OptiScaler#22]
I can't seem to get this installed. I have tried it on two games, Red Dead Redemption 2 and Dead Island 2 and it has a log but no errors so I have no clue as to whats wrong. I have a laptop but the keyboard has two insert keys, Fn method and Number lock method. I have tried changing keys in the settings file and didn't pop on. I reinstalled and didn't work. Any help, Thanks.

Edit: doesn't appear to be working either.

**Comment by cdozdil** [comment]
Hi,

Could you please share more information?
* Which OptiScaler version you have installed?
* Which method you have used for installing (nvngx or dxgi)?
* Have you enabled DLSS from game settings?
* Have you entered the game and waited 5-10 seconds before trying to open menu?
* Do you have any `OptiScaler.log` in game folder? If you have please share
* Have you tried to change menu shortcut from `nvngx.ini`?

```ini
; Shortcut key for opening menu
; Integer value - Default (auto) is 45 -> VK_INSERT (0x2D), previous default key VK_HOME is 36 (0x24) 
ShortcutKey=auto
```

**Comment by MaxMo20** [comment]
Thank you, I just recently got it working in RDR 2 I had to press the shortcut multiple times. I used the very latest version, dxgi, fr both games I enabled in game upscaler, I waited 5-10 seconds, and I do have a log for both games. I am looking to see if it is the same issue.

**Comment by MaxMo20** [comment]
[OptiScaler.log](https://github.com/user-attachments/files/16267811/OptiScaler.log)
This is the log for Dead Island 2

**Comment by cdozdil** [comment]
Looks like DLSS is not active, game does not load or create DLSS context.

**Comment by MaxMo20** [comment]
Thank you, I didn't realize it needed to be DLSS exactly so when you said "Looks like DLSS is not active in game options" I modded it in then ran the game. Now it pops on. Thank you!

**Comment by Harbi117** [comment]
I also have this issue in Metro Exodus Enhanced Edition.

- OptiScaler.v0.6.5-pre5
- DLSS is selected in-game and default XeSS is working
- I want to use FSR 3.1 but the menu won't pop up
- Found a workaround by going into ( nvngx.ini ) and changing the default upscaler

```
; Select upscaler for Dx12 games
; xess, fsr21, fsr22, fsr31, dlss - Default (auto) is xess
Dx12Upscaler=auto
```
to:
```
; Select upscaler for Dx12 games
; xess, fsr21, fsr22, fsr31, dlss - Default (auto) is fsr31
Dx12Upscaler=fsr31
```
[OptiScaler.log](https://github.com/user-attachments/files/16268809/OptiScaler.log)
^ This is the log from Metro Exodus Enhanced Edition

**Comment by cdozdil** [comment]
Hi, 

This is a known issue, Opti can't catch/capture game inputs with that game.

**Comment by xiaomanzai** [comment]
Monster Hunter: World is not working in the same problem. no log have be generated. I don't kown the reason why make this happen.

**Comment by cdozdil** [comment]
> Monster Hunter: World is not working in the same problem. no log have be generated. I don't kown the reason why make this happen.

Monster Hunter World is DLSS1, this mode is for DLSS2 and above.

**Comment by xiaomanzai** [comment]
> > Monster Hunter: World is not working in the same problem. no log have be generated. I don't kown the reason why make this happen.《怪物猎人：世界》并没有解决同样的问题。没有生成日志。我不知道为什么会发生这种情况。
> 
> Monster Hunter World is DLSS1, this mode is for DLSS2 and above.怪物猎人世界是DLSS1，该模式适用于DLSS2及以上。

Yes, I found this problem; Monster Hunter World is based on DLSS1.
