### ISSUE TITLE
Possible to implement forced anisotropic filtering?

### ISSUE THREAD

**Issue by aufkrawall** [cdozdil/OptiScaler#26]
Since OptiScaler can already force mip map bias, would it be possible to implement forced anisotropic filtering as an optional feature? The AMD D3D12 driver unfortunately still can't force it, and while forcing it may cause issues in some games, it can improve visuals in others where game devs e.g. apply questionable "optimizations" with low anisotropic filtering values for some textures etc.
Thanks!

**Comment by cdozdil** [comment]
Hi,

I have prepared a test build for anisotropy overriding. You can force it from `nvngx.ini` (better use this one) or from in-game menu. If you force it from menu probably need to change resolution or DLSS preset to activate changes.

```ini
[Hotfix]
; Override max anisotropy for textures
; 2, 4, 8, 16 - Default (auto) is disabled
AnisotropyOverride=auto
```

I have tried to limit override to Bilinear, Trilinear and Anisotropic filtered textures but might cause issues with menus and other 2D stuff.

[nvngx-force-aniso-test.zip](https://github.com/user-attachments/files/16411911/nvngx-force-aniso-test.zip)

**Comment by aufkrawall** [comment]
Thanks a lot for your efforts!

It seems with this build, there already is some issue with mip mapping (?) with default settings:
![witcher3_2024_07_29_15_31_01_283](https://github.com/user-attachments/assets/a2a75a13-83c8-434c-bc48-234103ecef59)

**Comment by cdozdil** [comment]
Ah yes made a copy/paste mistake, here fixed one 😊

[nvngx-force-aniso-test-2.zip](https://github.com/user-attachments/files/16414190/nvngx-force-aniso-test-2.zip)

**Comment by aufkrawall** [comment]
It works now, fantastic. :)

Probably a regression: It always shows the current mip bias as 0, whereas stable build v0.6.5 reports it as -2 with DLSS Performance selected in-game.

**Comment by cdozdil** [comment]
Yeah, noticed and fixed that after sending you the build 😊

**Comment by aufkrawall** [comment]
Hm, still shows 0. I've also noticed that saving the aniso value to config file from OSD doesn't work. :)

**Comment by cdozdil** [comment]
This build should fix both of the issues

https://github.com/cdozdil/OptiScaler/actions/runs/10170882440

**Comment by aufkrawall** [comment]
Confirmed fixed. :)

Maybe one more nitpick (hope this doesn't get too annoying): When adjusting only the aniso value in OSD and not touching the mip bias bar, I think it shouldn't force mip bias to 0 (both runtime and when writing to config).

**Comment by cdozdil** [comment]
Unless you click the set button it won't set mipbias. For anisotropy you don't need to click set, maybe putting anisotropy under set button makes it more obivous 👍

**Comment by aufkrawall** [comment]
Alright, makes sense. Closing now, thanks a lot! This is such an amazing tool.
