### ISSUE TITLE
Question: Sons Of The Forest

### ISSUE THREAD

**Issue by AerokoXF** [cdozdil/OptiScaler#27]
Hi i am new on this platform, if i get something wrong in the title or post please let me know.
Thank you.
So my question is can i use this “Mod” on a game called Sons Of The Forest?
The game uses DirectX11 and has the Upscaling options: DLSS, FSR 3.0 and FSR 1.0 and the standard presets: Quality, Balanced, Performance and Ultra Performance, i don't think these options enable Frame Generation, so the question is how do i
 install this “mod” and take advantage of Frame Gen?
A few attachments for more information.

Edit: I use RTX 20 Series

![Screenshot 2024-07-28 075708](https://github.com/user-attachments/assets/ea5696bd-e162-4d63-8f34-b0892ac4cc9b)
![Screenshot 2024-07-28 075745](https://github.com/user-attachments/assets/dce1f6cb-0463-4fcf-85cb-8acf6dc70121)
![Screenshot 2024-07-28 075911](https://github.com/user-attachments/assets/191120b4-4499-46e1-b9df-4979e6909f00)

**Comment by cdozdil** [comment]
Hi,

You can follow installations instructions, as far as I know Opti workis with SotF.

https://github.com/cdozdil/OptiScaler#installation-for-dlss-37-and-above-as-non-nvngx

**Comment by AerokoXF** [comment]
> Hi,
> 
> You can follow installations instructions, as far as I know Opti workis with SotF.
> 
> https://github.com/cdozdil/OptiScaler#installation-for-dlss-37-and-above-as-non-nvngx

I installed it and gained some FPS.
I thought it enabled Frame Gen but it did not.
In the options I noticed FSR 2.2.1 and DLSS 2.4.0

Excuse me for sounding ignorant but shouldn't I be accessing DLSS 3.7 or FSR 3.1?

**Comment by AerokoXF** [comment]
I installed it and gained some FPS.
I thought it enabled Frame Gen but it did not.

**Comment by Ridianoid** [comment]
> I installed it and gained some FPS. I thought it enabled Frame Gen but it did not.

This mod/app does not open frame generation. For that you need to use the DLSS enabler they work with. There is also optiscaler in that mod. If you are using an older version of optiscaler, here is a tutorial on how to update it. 

https://github.com/artur-graniszewski/DLSS-Enabler

**Comment by AerokoXF** [comment]
> > I installed it and gained some FPS. I thought it enabled Frame Gen but it did not.
> 
> This mod/app does not open frame generation. For that you need to use the DLSS enabler they work with. There is also optiscaler in that mod. Updating the old version optiscaler in DLSS enabler is explained in the tutorial here.
> 
> This mod allows you to change the disallowed upscale multiplier, play with sharpness, use it like DLDSR, change upscale with one click, etc. It can be confused with Frame Generation. That's not really the purpose. I use it together with lossless scaling. Hogwarts legacy looks amazing with the settings I made.
> 
> https://github.com/artur-graniszewski/DLSS-Enabler

Hello.
Thank you for your interest, i need as much help as possible.
I am new to this topic so it is very easy for me to make mistakes and not understand.
I can't quite understand the usefulness of this MOD/APP.
Inside the game (I put screens above) you can see the upscaling option: DLSS and FSR 3.0 with the various parameters: Quality, Balanced, Performance and Ultra Performance.
With this MOD/APP i noticed that by setting via game DLSS to Quality and via APP/MOD i put on balanced you don't notice much change in image, while in FPS i gain 5/10

**Comment by AerokoXF** [comment]
> > I installed it and gained some FPS. I thought it enabled Frame Gen but it did not.
> 
> This mod/app does not open frame generation. For that you need to use the DLSS enabler they work with. There is also optiscaler in that mod. Updating the old version optiscaler in DLSS enabler is explained in the tutorial here.
> 
> This mod allows you to change the disallowed upscale multiplier, play with sharpness, use it like DLDSR, change upscale with one click, etc. It can be confused with Frame Generation. That's not really the purpose. I use it together with lossless scaling. Hogwarts legacy looks amazing with the settings I made.
> 
> https://github.com/artur-graniszewski/DLSS-Enabler

I guess I can't install DLSS Enabler.
It only works with DX12 games.

> Simulate DLSS Upscaler and DLSS-G Frame Generation features on any DirectX 12 compatible GPU in any DirectX 12 game that supports DLSS2 and DLSS3 natively.

**Comment by Ridianoid** [comment]
> > > I installed it and gained some FPS. I thought it enabled Frame Gen but it did not.
> > 
> > 
> > This mod/app does not open frame generation. For that you need to use the DLSS enabler they work with. There is also optiscaler in that mod. Updating the old version optiscaler in DLSS enabler is explained in the tutorial here.
> > This mod allows you to change the disallowed upscale multiplier, play with sharpness, use it like DLDSR, change upscale with one click, etc. It can be confused with Frame Generation. That's not really the purpose. I use it together with lossless scaling. Hogwarts legacy looks amazing with the settings I made.
> > https://github.com/artur-graniszewski/DLSS-Enabler
> 
> I guess i can't install DLSS Enabler. It only works with DX12 games.
> 
> > Simulate DLSS Upscaler and DLSS-G Frame Generation features on any DirectX 12 compatible GPU in any DirectX 12 game that supports DLSS2 and DLSS3 natively.

Dude, upscale methods, frame generation / interpolation etc. You can learn what they do in software by asking chatgpt or gemini style AIs about software calculations. I didn't know the game was DX11, motion vector is not standard in DX11. Frame Generation needs motion vector to work. That's why you can't see the FPS increase that frame generation brings. You can only get a little FPS increase with upscale methods. I don't know if there will be CPU bottleneck or not. I found the updated version of the game from somewhere. I will download and test it. I will test it using only the FG feature according to whether Lossless Scaling can do something without motion vector. I will let you know.

**Comment by cdozdil** [comment]
Hi,

DLSS Enabler have full DirectX 12 and beta Vulkan support but sadly no DirectX 11 support. Enabler uses OptiScaler as upscaler backend and Nukem's mod as FG backend. Afaik Nukem's mod does not (and probably will not support) DirectX 11. So as long as game is not using Dx12 or Vulkan you are out of luck.

**Comment by AerokoXF** [comment]
Thank you so much for your helpfulness and in the help you have given me. 
I appreciated it so much!
I have one last question, i saw a MOD for GTA V that enable FSR 3.0 and DLSS, GTA V runs in DX11 so you can somehow enable Frame Gen on DX11 titles, is so i wondered, if i were a developer could i create this mod that ability FSR 3.0 and DLSS in SOTF?
Assumption

**Comment by Ridianoid** [comment]
> **Thank you so much for your helpfulness and in the help you have given me. I appreciated it so much!** I have one last question, i saw a MOD for GTA V that enable FSR 3.0 and DLSS, GTA V runs in DX11 so you can somehow enable Frame Gen on DX11 titles... (If this question is inappropriate because it finds its basis in outside sources, i will delete it. It is not my intention to disrespect the work of others.) Thank you

PureDark added motion vector by editing the shaders for it. Since it edits hundreds of them, it takes a lot of effort and you need to know how to do it.

**Comment by cdozdil** [comment]
Hi,

I am not used that mod but most probably as my Dx11withDx12 upscalers (which I get this idea from puredark's posts) he creates a D3D12 device and does all upscaling & fg stuff there and copies back result to the Dx11 side.

**Comment by AerokoXF** [comment]
I understand, so by working a lot on a game you can create the Frame Generation. That answers my question
That's okay, i thank you all for your help. I can also close the discussion.

**Comment by cdozdil** [comment]
There is LukeFZ's Uniscaler which can inject FG to games that does not support FG. It usually creates issues with UI elements (ghosting) but better than nothing. Ah it's a paid mod (like puredarks's mods) by the way.

**Comment by AerokoXF** [comment]
> There is LukeFZ's Uniscaler which can inject FG to games that supports DLSS/FSR/XeSS. It usually creates issues with UI elements (ghosting) but better than nothing. Ah it's a paid mod (like puredarks's mods) by the way.

Ah good to know, but i think i'll give up, i don't want during a gameplay the interface to start flickering or anything. 
Better to wait for something official. 
Anyway, i'm getting very interested in these topics, and it's really crazy what you guys have managed to do. 
That is to implement upscaling and frame gen even on unsupported games. It would be nice to have universal upscaling that works even on games that don't have DLSS and FSR options maybe an external upscaler.

**Comment by Ridianoid** [comment]
I tried, but it stays on the black screen. FG still doesn't work. I guess Uniscaler and Lossless Scaling somehow use the motion vectors that are standard with DX12 without using elements not added by the game developers. I haven't seen FG used in DX11 anywhere except PureDark, so it seems like a game-specific effort is needed. 

It seems like you need to buy new generation cpu and gpu to play Unity and DX11 based games. I tried it at 2K with everything on the highest setting. I put a 120 fps lock with 6800xt and 5800x3d and it plays almost without drops. But the game uses a lot of CPU. I don't know if I can see the advantage of x3D.
