### ISSUE TITLE
problems in alan wake 2

### ISSUE THREAD

**Issue by VelasquezZZ12** [cdozdil/OptiScaler#28]
I started playing Alan Wake 2 and I had this problem with ghosts or duplicates of the character when they move to the side, I'm playing on dlaa so it's acceptable but when I use the upscaler I get stuck, this only happens on the character,
how can I solve?I'll try to take better photos xD

![Alan Wake 2 30_07_2024 16_57_04](https://github.com/user-attachments/assets/59b72fdf-1800-4834-acba-6d1a383f1e7a)

**Comment by cdozdil** [comment]
If you are using with FG enabled, you can try the fixes suggested here

https://github.com/Nukem9/dlssg-to-fsr3/wiki/Alan-Wake-2

**Comment by VelasquezZZ12** [comment]
As always you saved me, thank you man
