### ISSUE TITLE
Crysis Remastered hangs upon exit (DX11)

### ISSUE THREAD

**Issue by cek33** [cdozdil/OptiScaler#30]
Hi, awesome work with upscaler. As stated above, Crysis Remastered hangs upon exit. Game is native DX11 only. I've tried installing Optiscaler both non-nvngx and as nvngx.dll. FSR2 2.2.1 is working normally at default settings (switching between XeSS and other FSR2 versions works also). Problem is possibly related to DX11 in general, because i can recreate same in Rise of Tomb Raider (which support both DX11 and DX12). It's only when DX12 is enabled game doesn't hang upon exit.

**Comment by cdozdil** [comment]
Hi, 

Could you try this build?

[nvngx.zip](https://github.com/user-attachments/files/16473727/nvngx.zip)

**Comment by cek33** [comment]
Thank you for swift response and solution, can confirm game properly shuts down now.
