### ISSUE TITLE
Changing UpscaleRatio and QualityOverrides with in-game menu

### ISSUE THREAD

**Issue by Dendari92** [cdozdil/OptiScaler#31]
Hello, thanks for your work on this awesome mod.

I'd like to ask if it's possible to change UpscaleRatio and QualityOverrides values while in-game, unfortunately so far I've been unable to do so and I'm not sure if I'm missing something.

See the following image, I've clicked on the checkboxes and changed the ratio values but as you can see on the bottom left of the in-game menu it doesn't seem to change the actual render resolution.
![image](https://github.com/user-attachments/assets/76046a4b-6618-4b63-9bb6-5923509a8681)

Btw changing the values in the .ini file works without problem but sometimes I'd like to change it on the fly depending on the game level.

**Comment by cdozdil** [comment]
Hi,

Most games query these values when changing a quality preset (Balanced -> Perf) or resolution. Most Unreal Engine games query these values once while booting up and use these values. Some rare games (HZD for example) query these values every frame and adjust render resolution according to new values. So this behavior is totally up to games approach but usually after changing ratios changing resolution helps.
