### ISSUE TITLE
alternate CAS as found in SweetFX feasible to avoid RCAS artifacts?

### ISSUE THREAD

**Issue by aufkrawall** [cdozdil/OptiScaler#32]
When applying RCAS with high strength, it can cause weird artifacts (as described in Config.md). The CAS shader in ReShade SweetFX can apply quite strong sharpen with e.g. a strength of 2.0, but doesn't seem to have this issue. Which is why I wonder if applying CAS like that could be feasible inside OptiScaler too?

**Comment by cdozdil** [comment]
Hi,

Funny thing is we started with CAS, because of these artifacts I have adapted RCAS (which prevented these issues.

Need to update issues page 😊

**Comment by aufkrawall** [comment]
With high RCAS sharpen strength, I'm getting weird bright image areas:

![witcher3_2024_08_02_12_13_57_446](https://github.com/user-attachments/assets/5aa951ef-e4c2-4994-9749-e69dd498c706)

Seems to be more distinct with FSR 3.1 than with XeSS.

**Comment by cdozdil** [comment]
I have used this shader as referance, could you check if it's producing similar issues?

https://github.com/RdenBlaauwen/RCAS-for-ReShade/blob/main/RCAS.fx

**Comment by aufkrawall** [comment]
The issue does not occur with that RCAS shader used in ReShade.

**Comment by cdozdil** [comment]
Hi, 

Could you try this build?

[nvngx.zip](https://github.com/user-attachments/files/16473727/nvngx.zip)

**Comment by aufkrawall** [comment]
It doesn't seem to occur with this build, but the sharpen effectiveness of RCAS also seems to be reduced to (almost?) non-existent.

**Comment by cdozdil** [comment]
Hi,

I just checked on some games on my notebook, RCAS seems to be working?

**Comment by aufkrawall** [comment]
Yeah, however with that new build, it looks way softer than RCAS via ReShade at the same strength:

![witcher3_2024_08_03_10_36_03_447](https://github.com/user-attachments/assets/de034436-52e7-480f-9238-3a2cd21c1b81)

![witcher3_2024_08_03_10_36_26_858](https://github.com/user-attachments/assets/a14dadda-65fb-4f7e-8348-46e8e5b1b23b)

**Comment by cdozdil** [comment]
Hi,

Thanks for pointing this out, I found a mistake on my shader code (multiplied with denoise value twice).
Could you check if this build fixes the issue?

[nvngx.zip](https://github.com/user-attachments/files/16479016/nvngx.zip)

**Comment by aufkrawall** [comment]
Thanks! They are closer to each other now (I also forgot to re-enable the denoiser in the ReShade shader for the previous screenshots...), but I think ReShade is still a tad sharper?

![witcher3_2024_08_03_16_36_21_731](https://github.com/user-attachments/assets/235b524e-c80c-4741-bf17-08c92bf801b3)

![witcher3_2024_08_03_16_37_22_772](https://github.com/user-attachments/assets/b30fadc0-d56a-4271-bf1d-8d77fa3e6ad7)


The ReShade shader also allows to enter a sharpen strength of up to 1.3 (I used 0 though), maybe that would be the cheapest way to get to higher sharpen strength in OptiScaler? 🐸  As FSR 3.1 also is quite soft.

**Comment by cdozdil** [comment]
Yeah, that was in my mind too. I will check and adapt it later today 👍🏻

**Comment by cdozdil** [comment]
Ok, prepared another test build.

[nvngx.zip](https://github.com/user-attachments/files/16482852/nvngx.zip)

**Comment by aufkrawall** [comment]
Thanks, it definitely works now to get higher sharpen without the previous artifacts! :)
If I were nitpicky, I'd say the shader via ReShade still sharpens the image a bit more evenly. But you probably have far more exciting stuff on your agenda. Thanks again!

**Comment by cdozdil** [comment]
Thanks for helping me to sort out this issue 👍
