### ISSUE TITLE
Feature request: force pixel jittering

### ISSUE THREAD

**Issue by AleksNo** [cdozdil/OptiScaler#36]
Hello, the game Final Fantasy 14 online has introduced new antialiasing options. And OptiScaler works great with it, thank you. But the game has one issue: in some circumstances like cutscenes or /gpose the pixel jittering is disabled. And this effectively disables all TAA-based antialiasing mechanisms. Is there a possibility to force the pixel jittering if a game disables it? 

Thank you.

**Comment by cdozdil** [comment]
Hi,

Sadly it's other way around. Game generates jittered images along with other stuff (depth, mv etc.) sends it to upscaler. I have no way to force game to generate jittered images.

**Comment by AleksNo** [comment]
OK, thank you. :)
