### ISSUE TITLE
[Horizon: Zero Dawn] Flickering trees with OptiScaler

### ISSUE THREAD

**Issue by Ryusennin** [cdozdil/OptiScaler#38]
System: Win10 + Radeon 6650 XT (AMD Software 24.7.1)

The trees occasionally flicker when getting closer to them. Maybe it's during a change of mipmaps or LODs?

It's a difficult bug to reproduce because it doesn't seem to happen everywhere, but in some wooden places (east of Devil's Grief for example) it's quite recurring.

I've tried several versions of OptiScaler without any difference. It happens no matter which upscaler I select (FSR2, FSR3), it even happens without selecting any upscaler. It's enough that OptiScaler is installed in the game folder and DLSS appears available in the display menu.

It doesn't happen when OptiScaler is not installed. It doesn't happen either with the old Goghor mod (DLSS Unlocker), although you need to use version 2.1b (other versions have a lot of ghosting).

https://www.nexusmods.com/horizonzerodawn/mods/133?tab=files&file_id=474

**Comment by cdozdil** [comment]
Hi,

If it's possible could you share video of issue? A normal one and a problematic would be great.

**Comment by Ryusennin** [comment]
I'll try that soon, though the flicker occurs for a split second and I'm not sure it will be visible on video.

**Comment by Ryusennin** [comment]
Here are the videos:

o Correct display (DLSS Unlocker)
https://youtu.be/uqXVLszXMGg

o Trees flickering (OptiScaler)
https://youtu.be/68Q7IQ3h93E

**Comment by cdozdil** [comment]
Hi,

After experimenting with mods I have found the issue. This flicker is happening because of Nvidia spoofing. Even without OptiScaler is I put dxgi.dll (d3d12-proxy) it happens. Good news is you can use Goghor's winmm.dll + OptiScaler and flicker disappers. Just don't forget to set Dxgi=false from nvngx.ini, to disable Nvidia spoofing.

**Comment by Ryusennin** [comment]
It works! Thanks a lot for your expertise 💯
