### ISSUE TITLE
[FR] linuxinstall.sh not found in the repository (Instructions for solution mentioned)

### ISSUE THREAD

**Issue by nimbold** [cdozdil/OptiScaler#4]
Hi, first of all thanks for the amazing work!
The problem was/is that there's no **linuxinstall.sh** in your repository, but I've found it in the **CyberFSR2** one and then I tinkered with it a bit to find the solution for my games.

- Instructions:

Here's what I've changed to make **Crysis Remastered (Epic/Heroic version)** work with your implementation of FSR2.2:
`heroic(){
    home=$(echo ~)
    home=/run/media/nima/sda1/Games/Heroic/Crysis remastered/pfx/drive_c/Games/Crysis Remastered
    echo "I am going to run this command, are you sure?"
    echo "WINEPREFIX=$home /bin/wine64 regedit EnableSignatureOverride.reg"
    read -p "Press [Enter] to continue..."
    WINEPREFIX=$home /bin/wine64 regedit EnableSignatureOverride.reg

}`

The original **linuxinstall.sh** file can be downloaded here: 

> https://github.com/PotatoOfDoom/CyberFSR2/blob/main/linuxinstall.sh

It would be awesome if you could add the raw file into the repository. Thanks a lot!

**Comment by cdozdil** [comment]
i will update instructions soon, thanks for heads up

**Comment by FakeMichau** [comment]
It's not a very good script - assumes a lot things, works only on a single game unless you dive into the code which kinda defeats the purpose. 
In that case might as well do ``WINEPREFIX=pfx wine regedit EnableSignatureOverride.reg`` and tell the users where to find the correct prefix for their own setup or in case of steam games - to use protontricks, select the game, open the regedit and import the file.
Could you take a look at the current [instructions](https://github.com/cdozdil/OptiScaler?tab=readme-ov-file#installation) and give your feedback on them?

**Comment by nimbold** [comment]
Thanks a lot for the updated instructions, it works a lot easier! 
Now for the Heroic launcher I just used Wintricks to launch Regedit and then imported the EnableSignature file. It was weird that I should do it twice, but it worked in the end! 
Thanks for all the work you're doing🍻
