### ISSUE TITLE
Black Myth: Wukong mod application

### ISSUE THREAD

**Issue by VelasquezZZ12** [cdozdil/OptiScaler#40]
I wanted to know if you are going to audition for Black Myth: Wukong
 I took the test on Benchmark Tool
It worked but the image looked strange, it was a bit broken in the vegetation, FG came first so you can't use xess or dlss, unfortunately only the mods to save

**Comment by cdozdil** [comment]
Hi there,

Could you try with [this build](https://github.com/artur-graniszewski/DLSS-Enabler/releases/tag/3.01.001.0-beta5) of DLSS Enabler

**Comment by VelasquezZZ12** [comment]
I made this recording to try to catch this error that happens, you can see it in the trees and also in the dry branches when the mod is activated the vegetation looks very ugly and with artifacts, the native one is perfect without errors but it would be incredible to use the mod in the game 4k recording link on youtube https://youtu.be/Ep1103jslqs

**Comment by cdozdil** [comment]
Hi,

It looks like upscaler (FSR in this case) issue. Feels like some issue with motion vectors. Could you try different versions of FSR, maybe 3.1? It's usually performs better with less/missing MV info than 2.X.

**Comment by VelasquezZZ12** [comment]
I tested all the upscalers and I did 3.1 and unfortunately no improvements
