### ISSUE TITLE
testing the mod on ff16

### ISSUE THREAD

**Issue by VelasquezZZ12** [cdozdil/OptiScaler#50]
I tested the mod and had this problem, I think it's character synchronization.
I also tested the reflection, it's great and the mod's upscaler is better than the game's, I just had this error.
https://www.youtube.com/watch?v=oO1Iq3FYMz4
Any ideas for a fix?

**Comment by cdozdil** [comment]
I noticed one dark frame after leaving menu, is it the problem?

**Comment by Monnigkeit** [comment]
> I tested the mod and had this problem, I think it's character synchronization.
> I also tested the reflection, it's great and the mod's upscaler is better than the game's, I just had this error.
> https://www.youtube.com/watch?v=oO1Iq3FYMz4
> Any ideas for a fix?

How did you get it Working For me it don’t Start the Game
