### ISSUE TITLE
Optiscaler pre8 causing crash on tekken 8 and kena

### ISSUE THREAD

**Issue by Androdiver** [cdozdil/OptiScaler#51]
Pre7 is working fine just pre8 is causing crash on kena and tekken 8 both game uses unreal engine don't have any other unreal engine game to make further clarifications. I also tested pre8 on shadow of  the tomb raider, Rise of the tomb raider and rift apart it was fine with those games

**Comment by cdozdil** [comment]
Could you share more info and provide logs please?

**Comment by cdozdil** [comment]
Also could you try this build, if issue still persists.

[nvngx.zip](https://github.com/user-attachments/files/17066018/nvngx.zip)

**Comment by Androdiver** [comment]
> Also could you try this build?
> 
> [nvngx.zip](https://github.com/user-attachments/files/17072356/nvngx.zip)

This one have no crash

**Comment by cdozdil** [comment]
Ok merged this changes to pre9, thanks for reporting 👍🏻
