### ISSUE TITLE
suspected youtube malware

### ISSUE THREAD

**Issue by toxicfox2491** [cdozdil/OptiScaler#52]
so I was looking for ways to get DLSS or FSR running on games under my windows VM so I started searching and I found a video stating it can get DLSS on GTX cards, thought there might be a catch and there was...
its an AI voice over the video and isnt linking directly to the github page instead they're distributing release files through a site called sharemods. I suspect its been tampered with and probably contains malware
I just want to make you aware of this incase you wheren't already because videos like this tend to get copied and pasted over and over again
https://www.youtube.com/watch?v=pkvse7Ldiss

**Comment by toxicfox2491** [comment]
I did also try to mention the github page in comments and it gets automatically removed

**Comment by cdozdil** [comment]
Hi,

Thanks for heads up. We (me and other mod devs) are aware of this situation but there is not so much to do about it (and I don't wanna spend energy on it). These "YouTuber"s are even sharing paid mods like LukeFz's ones. 

They are using sharemods in hope of earning money from downloads. No sure how successful they are tho 😊

**Comment by toxicfox2491** [comment]
gonna close this now :3
just wanted to make you aware ppl where doing this in case you wherent
