### ISSUE TITLE
GUI not visible in God of War Ragnarok - 0.6.7-pre8

### ISSUE THREAD

**Issue by rigopoui** [cdozdil/OptiScaler#53]
Optiscaler works fine, but the gui itself is not visible when pressing Insert. The dialog popup kinda works, in that it does block input as if it is visible.

**Comment by cdozdil** [comment]
Hi,

Could you try build shared here?

https://github.com/cdozdil/OptiScaler/issues/51#issuecomment-2362114481

**Comment by cdozdil** [comment]
Fixes added to [pre9 build](https://github.com/cdozdil/OptiScaler/releases/tag/v0.6.7-pre9)
