### ISSUE TITLE
[DX11] [FSR3.X] [SteamOS] God of War (2018) crashes in SteamOS under FSR 3.X

### ISSUE THREAD

**Issue by Txordi00** [cdozdil/OptiScaler#70]
God of War (2018) on Steam Deck (main branch, 3.7 ATM) crashes when using FSR 3.X in OptiScaler 0.6.7 final.

It is installed as `dxgi.dll`. This is the output of `ls` in the game's folder:
`amd_fidelityfx_dx12.dll  dxgi.dll   GoW.exe               libSceJobManager.dll  nvngx.dll       OptiScaler.log   vkd3d-proton.cache
amd_fidelityfx_vk.dll    dxvk.conf  libSceGnm.dll         libScePad.dll         nvngx_dlss.dll  settings.ini     vkd3d-proton.cache.write
bink2w64.dll             exec       libSceGpuAddress.dll  libxess.dll           nvngx.ini       steam_api64.dll
`

Before that I was using 0.6.7-pre11 and FSR 3.1 was working, but was giving noticeably worse image quality in comparison with FSR 2.2 and the original FSR 2.0 implementation. Performance was about the same. In addition, I noticed that this game looks much better with `reactive mask` disabled.

I launch the game from steam with the following launch options: `WINEDLLOVERRIDES=dxgi=n,b PROTON_FORCE_NVAPI=1 %COMMAND% ` in the game steam properties.

Here is a video of the issue: https://vk.com/video646854078_456239019?list=ln-4cGRpgE6wSWEezoL43

This is the `nvngx.ini` file (everything set at default values): [nvngx.txt](https://github.com/user-attachments/files/17275875/nvngx.txt)

And the debug-level log (I believe) taken at the time of the above video: [OptiScaler.log](https://github.com/user-attachments/files/17275870/OptiScaler.log)

Hope I did provide all the necessary info! Thanks for your help and for your amazing work!!! Hope we can fix this issue, bye! :)

EDIT: I tried v0.7.0-pre9 and it's the exact same issue. I tried as well to launch directly with  `Dx11Upscaler=fsr31` to no avail. It freezes and crashes right after launch.

**Comment by MapleHinata** [comment]
Fixed with #71 
![PXL_20241007_231641057](https://github.com/user-attachments/assets/6c6740a6-e75e-4a33-b2ce-966eb797a6cb)

**Comment by Txordi00** [comment]
Amazing! Thanks a lot! I'll wait a new build then! )
