### ISSUE TITLE
Crysis Remastered (1,2) - No DLSS option active in menu

### ISSUE THREAD

**Issue by donizettilorenzo** [cdozdil/OptiScaler#8]
As title says, with the last versions (I build them with VS 2022) the DLSS option is greyed out.

**Comment by cdozdil** [comment]
Hi there, 

Just tried running Crysis 2 Remastered and it's ok. Maybe you forgot `dxgi.dll` ? 

![image](https://github.com/cdozdil/OptiScaler/assets/35529761/90399311-8967-4bd1-a4d9-0dd47939116c)

**Comment by donizettilorenzo** [comment]
It never was necessary before!

**Comment by cdozdil** [comment]
Looks like you are right, it works without dxgi.dll too. Just made a release try that one 
https://github.com/cdozdil/OptiScaler/releases/tag/v0.6.0-pre3

**Comment by donizettilorenzo** [comment]
New (pre)release is working!

Question: if I put DLSS 3.7 DLL in every DLSS game
1) I still need the override reg key?
2) I must do the new renaming procedure in every game?

**Comment by cdozdil** [comment]
You don't need to put 3.7 DLSS in games, new games start coming with DLSS v3.7 which disabled disable dignature check bypass. You need to use this new spoofing only for games whick compiled with DLSS 3.7 SDK

**Comment by donizettilorenzo** [comment]
I know, but the question was about me putting the 3.7 DLSS in older games to play with my GeForce AND THEN pluggin in an Intel GPU and use OptiScaler with it. Because I can see that doing so (no more GeForce on the system but 3.7 DLSS is in multiple game folders) something is wrong with OptiScaler. Putting the old DLSS back solves the problems.

**Comment by cdozdil** [comment]
Ah I wasn't expecting this aproach (Nvidia/Intel). My safe bet would be `nvngx_dlss.dll (v3.7) -> nvngx.dll` and Opti `nvngx.dll ->dxgi.dll`. 

By putting these 2 files in game's exe folder in theory both cards should be fine.
