### ISSUE TITLE
Spider-Man Remastered

### ISSUE THREAD

**Issue by Ridianoid** [cdozdil/OptiScaler#9]
Hello. I have a problem with Spider-Man Remastered. I installed dxgi.dll and the latest version files with only optiscaler. PC freezes completely at the sony logo. I have to turn it off by pressing the power button. I tried the original version 2.616 and 2.1012 with no results. There is a version like 2.217 with crack. I tried that too and the same thing happens again. Can you check it? Thank you. 

nvngx_dlssg.dll versions; https://i.imgur.com/Ol4Xgwk.png

Specs; 6800xt, 5800x3d with Windows 10

**Comment by cdozdil** [comment]
Hi,

Could you try game with this build? 

https://github.com/cdozdil/OptiScaler/actions/runs/9332731828

Also if you are using RTSS could you try closing it or enabling Microsoft Detours in RTSS settings.

**Comment by ridoknight** [comment]
> Hi,
> 
> Could you try game with this build?
> 
> https://github.com/cdozdil/OptiScaler/actions/runs/9332731828
> 
> Also if you are using RTSS could you try closing it or enabling Microsoft Detours in RTSS settings.

I tried, mate. I'm afraid it didn't work. Even though there is DLSS in the mini launcher, FG does not seem active again. 
https://i.imgur.com/OnGDmlh.png

And it freezes just like this. I've turned off everything running in the background, only fancontrol and displaycall are working. 
https://i.imgur.com/Cm2Fh7d.jpeg

**Comment by cdozdil** [comment]
If you are aiming for FG you are using wrong mod, please check here [DLSS Enabler](https://www.nexusmods.com/site/mods/757)

Will try to check that freezing issue.

**Comment by ridoknight** [comment]
> If you are aiming for FG you are using wrong mod, please check here [DLSS Enabler](https://www.nexusmods.com/site/mods/757)
> 
> Will try to check that freezing issue, one more thing could you set `OverlayMenu=false` from `nvngx.ini` and try again. Let's see if new menu hooks messing up something.

Oh ok. It froze just like that, so I found the mode when I came up with alternative methods. As you said, I turned off Overlaymenu and steam overlay, this time I came to the next spider save logo from sony and froze again. With Uniscaler, it freezes the same way when DLSS is selected. I've never tried that. I don't understand there is a change in the DLSS base. I burnt my video card 15-16 years ago when I switched off the PC by pressing the power button. That's why I'm scared every time. I wish I could give you a log or something, that would be great. 


I tried in Icarus dx12, FG was not activated, as you said, but the overlay came with the Insert key. With XESS, small coloured squares appeared everywhere, decreased with FSR but still there. They seem to appear on the edges of objects. Probably fine tuning is required. I will look at the Configuration section. Thank you.

**Comment by cdozdil** [comment]
Hi there, just installed game and it works with `dxgi.dll` + `nvngx.dll` mode.

![image](https://github.com/cdozdil/OptiScaler/assets/35529761/141964e3-0be4-49d4-b384-91b46939d2a0)
![image](https://github.com/cdozdil/OptiScaler/assets/35529761/0c40b88a-f5c9-490c-90ce-b504579db0bb)

My game folder:  
![image](https://github.com/cdozdil/OptiScaler/assets/35529761/ebbecf7f-f74f-409d-83ef-682a30c31c58)

**Comment by ridoknight** [comment]
Thank you for your time. My fears have come true. I was hoping there wouldn't be some stupid system problem, and there was. I did a DDU and uninstalled and reinstalled the drivers and nothing changed. I re-downloaded everything except d3d12 and asset_archive folder by deleting and verifying everything except d3d12 and asset_archive folder, saying that the previous mods left a residue etc. I turned Signature off and on again, I tried Windowed mode, it does not work. The computer completely locks up. Nothing like this has ever happened to me in any other game. Driver is the most up to date version, does that matter? I will definitely not be able to sleep at night because of this :/

**Comment by cdozdil** [comment]
I can offer an alternative method not sure if it would change anything 
1. Delete dxgi.dll (d3d12-proxy)
2. Rename my mod to dxgi.dll
3. Make a copy of nvngx_dlss.dll and rename it to nvngx.dll
Try running game again

**Comment by ridoknight** [comment]
> I can offer an alternative method not sure if it would change anything
> 
>     1. Delete dxgi.dll (d3d12-proxy)
> 
>     2. Rename my mod to dxgi.dll
> 
>     3. Make a copy of nvngx_dlss.dll and rename it to nvngx.dll
> 
> 
> Try running game again
> 
> Ah also maybe changing default upscaler to fsr21 might help. Maybe issue is XeSS

Before I tried this, I tried resetting the launcher and boom the game opened. The problem was Ray Tracing. I maxed everything, I entered the game again, no problem. But when I open RT, the PC locks up. Can you try and take a look at it? When I use only FG and your mod settings in Lossless Scaling, I can play 2k DLAA 120 fps locked with 150w :D Looks great. Thanks a lot. 

![2024-06-02 20_59_43-Greenshot](https://github.com/cdozdil/OptiScaler/assets/20602186/be8a0bfa-1830-426a-b46c-efeef98f2263)

**Comment by cdozdil** [comment]
I remember something about RT, will ask Artur, developer of DLSS Enabler 👍

**Comment by cdozdil** [comment]
Hi again,

When you have time could you try this:

1. Copy nvapi64.dll to game folder from this file : [nvapi-dummy](https://github.com/FakeMichau/nvapi-dummy/actions/runs/9255718333)

2. Then set `OverrideNvapiDll=true` in `nvngx.ini`

In theory if game is querying NvApi, with this dll we might prevent some Nvidia specific RT path.

**Comment by Ridianoid** [comment]
> Hi again,
> 
> When you have time could you try this:
> 
>     1. Copy nvapi64.dll to game folder from this file : [nvapi-dummy](https://github.com/FakeMichau/nvapi-dummy/actions/runs/9255718333)
> 
>     2. Then set `OverrideNvapiDll=true` in `nvngx.ini`
> 
> 
> In theory if game is querying NvApi, with this dll we might prevent some Nvidia specific RT path.

Unfortunately, the computer froze again with RT options.

**Comment by cdozdil** [comment]
Hi,

Sorry to hear that nvnap64.dll does not helped. To understand the issue better could you try this? 

Rename `nvngx.dll` to `nvngx.bak` and run game with only `dxgi.dll`. 

We are trying to understand if using `dxgi.dll` is triggering some Nvidia specific codepath which leads up to freezing issue.

Also could you send me picture of game folder, any other mods are installed maybe?

**Comment by Ridianoid** [comment]
Çetin abi I try to keep it in English so that it is more universal and does not contradict the language of the project. Mosf of time I use it in translation :D 

I actually mentioned above.  But maybe my English was not enough to explain :D I deleted all the files except the `d3d12` folder and the folder starting with the `asset` because I added and removed a lot of things in the general game folder. Then I verified on steam and it pulled all the files it needed. I didn't install Turkish either, my only mod was to FG. 

Since I finished the game yesterday, I don't plan to install anything except your mod. I'll just play in to make it 100%. In the meantime, if we can find a solution to this, it will be great. 

Can you open RT with your 6950xt? 

Other than that, I will do what you said when I get home and take a screenshot of the folder. I will even share the folder byte. Maybe there has been a change in the folders I did not delete.

**Comment by cdozdil** [comment]
Pardon fark etmemişim durumu.

Öngörümüz şu şekilde, `dxgi.dll` dosyası senin ekran kartını 4090 olarak tanıttığı için oyun da Nvidia'ya özel kod bloklarını aktive ediyor ve bu da senin sisteminin donmasına sebep oluyor. Bunu test edebilmek için; 

1. `nvngx.dll` dosyasını `nvngx.bak` ya da `nvngx-yedek.dll` vb şekilde yeniden adlandıralım
2. `dxgi.dll` kalsın, ona dokunmayalım
3. Oyunu RT aktif tekrar başlatalım

Eğer takılma olursa problem `dxgi.dll` ve 4090 spoofing demektir. Bunun için de 1-2 geliştirme yaptık (sadece Streamline'a 4090 raporlamak vb.) ama pek denenmedi açıkçası. Sürekli sistemin takıldı için denemelerde çok da üstelemek istemiyorum açıkçası, uzatmayalım dersen sıkıntı yok.

Bende ne yazık ki 6950XT ekran kartı yok, o Discord sunucusunda teste yardımcı olan arkadaşlardan birinin kartı.

**Comment by Ridianoid** [comment]
Tamam abi. Yok yok çözelim bunu. Nixxess yeni nesil Sony oyunlarının çoğunu yapacak gibi ve adamlar hangi şirkette en güncel ne varsa onu implemente ediyorlar. FSR 3.1de bunların Rochet and clankde test edilip tsushima da eklendi sanırım. O yüzden DLSS yakasında da yeni ne gelirse hemen adapte olacak gibiler. 

Bu RT için ne yapıyorsa ona bir çözüm üretilmiş olsun da optiscaler'ın geleceği için bir adım daha yürümüş oluruz. Ben test ederim. Sadece eski bir tecrübeden bahsetmek istemiştim. Şimdi güç kaynağım iyi o yüzden 12vdan ters bir voltaj gönderip zarar vereceğine inanmıyorum. 😬

Ben de DC geleyim onu kaçırmışım.

**Comment by Ridianoid** [comment]
`nvngx.dll `dosyasını `nvngx.bak` yapınca bırak oyunun açılmasını launcher bile gelmiyor abi. Tıklar tıklamaz hata gelmiyor ama bir 30 saniye bekliyorsun sonra sony crash'ı geliyor. 

![2024-06-03 15_43_11-Greenshot](https://github.com/cdozdil/OptiScaler/assets/20602186/f30bdf62-15a7-429f-8b3f-42a3903310d4)

bak'ı silip tekrar eski haline getirince launcher burada. 

![2024-06-03 15_42_23-Greenshot](https://github.com/cdozdil/OptiScaler/assets/20602186/455cf12a-67c0-4071-a39f-d1a8d9934241)

Dedim belki bana özel yaptığın opti sürümünde sorunu başka yerde aradık ya bir de v0.6.0-pre3'ü deneyeyim. Bu şekilde yapınca launcher geldi. Yukarıda önerdiğin `nvapi64.dll`'yi ekledip iniyi değiştirerek ve bunları silerek 2 türlü denedim. İkisinde de launcher geldi ama sony logosunda sistem yine kitlendi. 

![2024-06-03 15_58_17-Greenshot](https://github.com/cdozdil/OptiScaler/assets/20602186/be256cc2-2c2b-434e-9fd3-dfec93803f46)

**Comment by cdozdil** [comment]
Tamamdır, çok sağol denediğin için. Ben 1-2 kontrol yapayım sana dönüş yapacağım 👍

**Comment by cdozdil** [comment]
Selam, 

`Belgelerim` (Documents) klasöründe `Marvel's Spider-Man Remastered` klasöründe `Marvel's Spider-Man Remastered.log` dosyası olması lazım. Bu dosyayı burada paylaşabilir misin acaba?

**Comment by Ridianoid** [comment]
[Marvel's Spider-Man Remastered.log](https://github.com/user-attachments/files/15536184/Marvel.s.Spider-Man.Remastered.log)
[Marvel's Spider-Man Remastered-v2.1012.0.0 2024-06-03-15-52-25.zip](https://github.com/user-attachments/files/15536198/Marvel.s.Spider-Man.Remastered-v2.1012.0.0.2024-06-03-15-52-25.zip)

bir de dmp dosyası vardı onu da ekledim. Belki bir işe yarar.

**Comment by Ridianoid** [comment]
Çetin abi, çok ilginç bir durum yaşıyorum. Bu, Spider-Man oyunuyla birlikte başladı ya da ben o zaman fark ettim. Mouse'u normal şekilde hareket ettirirken anlık takılmalar yaşıyodum. Oyuna girdiğimde 60 FPS alırken aniden 57'ye düşüyor ve shutter yapıyordu. Bunu Unreal Engine sorunu sanıyordum ama masaüstünde, tarayıcı sekme açarken veya aşağıda halihazırda çalışan bir pencerenin üzerine giderken de aynı şey oluyordu.

Dün DDU ile sürücüyü silip yeniden yüklediğimi söylemiştim ya ondan sonra düzeldiğini farkettim. Bu spoof için yüklediğimiz regedit ayarı veya başka bir şey GPU'da bir sorunlara sebep oluyor gibi görünüyor.

Şimdi yine aynı takılmaları yaşadım. Çünkü Eve gelince kitlenme testi yapmıştım. DDU öncesi Radeon uygulaması üzerinden fabrika ayarlarına sıfırlama yaptım ama işe yaramadı. Şimdi  sürücüyü tekrar silip yükledim. Masaüstünde takılma veya donma problemi şu an 1 saattir yok.  

Hogwarts'a senin modun ve lossless scaling ile gireceğim. Bakalım FPS ne yapacak.

**Comment by Ridianoid** [comment]
Abi bu sorun beni delirti. Takılmayı geçirememeye başladım. Bu sefer hiç hoşlanmasam da format attım bilgisara. Bu sefer donma olmadı ama hata aldım. Hata da şu şekilde belki bir işine yarar.

![untitled](https://github.com/cdozdil/OptiScaler/assets/20602186/d6d324ee-7a53-4087-8c8c-483c29d1f8cf)

**Comment by cdozdil** [comment]
Bu hata Nvidia RT özellikleri aktifken benim Arc 750'de de geliyor. Henüz buna bir çözüm üretemedik (Açıkçası pek de bu konuya odaklanmadık henüz).

**Comment by Ridianoid** [comment]
Abi merhabalar. Hogwarts Legacy bugün büyük bir güncelleme aldı. 3.7.0 eklemişler. Pre buildde anlattığın gibi DLL değiştirmeleri vs yaptım. DLSS seçeneği geldi fakat Ins tuşuna basınca overlay gelmiyor. Ekran bembeyaz kalıyor. Önceki sürümde de bu şekilde olmuştu ama opti overlay gelmişti color ve motion'ı değiştirerek oyunu oynayabilmiştim.

**Comment by cdozdil** [comment]
Selam,

Sana daha önce önerdiğim https://github.com/cdozdil/OptiScaler/actions/runs/9332731828 ile dener misin durum aynı mı?

**Comment by Ridianoid** [comment]
> Selam,
> 
> Sana daha önce önerdiğim https://github.com/cdozdil/OptiScaler/actions/runs/9332731828 ile dener misin durum aynı mı?

Çalıştı abi. Çok teşekkür ederim ^^

**Comment by Ridianoid** [comment]
@cdozdil abi tekrardan merhabalar. Bu oyun içindeki SAVE INI butonu tam olarak neyi nereye kaydediyor? Oyun exe içindeki klasördeki nvngx.ini kontrol ettim ama orada bir değişiklik yapıyor gibi durmuyor. Oyun içindeki ayarlarımı mip bias hariç hatırlıyor. Onun için bir mip bias değeri vereceğim. Benim mi gözümden kaçtı bilemiyorum bir türlü bulamadım nereye kaydettiğini.

**Comment by cdozdil** [comment]
Selam,

`nvngx.ini`içindeki `MipmapBiasOverride` kısmını kullanabilirsin

```ini
; -------------------------------------------------------
[Hotfix]
; -------------------------------------------------------
; Force remove RESPONSIVE_PIXEL_MASK from init flags
; true or false - Default (auto) is true
DisableReactiveMask=auto

; Override mipmap lod bias for textures
; -15.0 - 15.0 - Default (auto) is disabled
MipmapBiasOverride=auto
```

kayıtta dalgınlıkla bir hata yapmışım onu da düzelttim. 0.6.1'de düzelmiş olacak, çok sağol 👍

**Comment by Ridianoid** [comment]
![2024-06-20 22_52_23-Greenshot](https://github.com/cdozdil/OptiScaler/assets/20602186/a0b2d354-e9a8-4728-bc91-731e1301703a)

Onu denedim abi. Olmadı. SS'de de ekledim. ini dosyası düzenlenmiş halde. Maalesef etki etmedi. Hatta çoğu dosya açık kapalı bir değerler girili ama save ini butonu neyi nereye kaydediyor bilemiyorum ini dosyasında her şey autoda görünüyor. 

Ben teşekkür ederim abi. Harika ötesi bir mod olmuş. DLSS Enabler gibi FG aktive etmek için yola çıktım. Yaşadığım bir sorundan ötürü çözüm bulurum diye bu modu buldum ama şimdi Optiscaler ile Lossless Scaling kullanıyorum. Muhteşem 2'li :D

**Comment by cdozdil** [comment]
Selam,

Mipmap ayarının aktif olması için bir kez çözünürlüğü değiştirmen gerekiyor ne yazık ki, 1080->720->1080 yap mesela aktif olduğunu göreceksin.

**Comment by Ridianoid** [comment]
Abi merhabalar. Bugün bütün nixess PS portlarına FSR 3.1 desteği geldi. Spider-man'e güncelleme yapıyorum. FSR 3.1'i de optiscaler'a eklemek için bir fırsat olabilir mi bu? Veri elde edebilir misiniz bundan? Editlenen veya eklenen dosyalar bunlar;

![2024-06-27 20_00_11-Window](https://github.com/cdozdil/OptiScaler/assets/20602186/bc8ddca7-5e38-47e7-b974-7673dfaaee54)

**Comment by cdozdil** [comment]
Selamlar,

Dosyalar bende de mevcut fakat AMD API'yi değiştirmiş (daha moduler olabilmesi için). 
Temmuz'da kaynak kodunu yayınlayacağını açıkladı, onu bekleyeceğiz.

**Comment by cdozdil** [comment]
Selam,

Bu sürümü `dxgi.dll` olarak kullanırsan `nvngx.ini` dosyasında belittiğin MipMap değerini çözünürlük ya da kalite değiştirmeden en baştan itibaren kullanabilirsin. 

[OptiScaler.v0.6.2-pre5.zip](https://github.com/user-attachments/files/16072042/OptiScaler.v0.6.2-pre5.zip)

> Yine olmadı abi. -1.3 yaptı bu sefer. Neyse her türlü çözünürlük değişimi gerekiyorsa kendim elle ayarlarım. Ben oyun başlarken kendisi yapar diye düşünmüştüm.

**Comment by Ridianoid** [comment]
> Selam,
> 
> Bu sürümü `dxgi.dll` olarak kullanırsan `nvngx.ini` dosyasında belittiğin MipMap değerini çözünürlük ya da kalite değiştirmeden en baştan itibaren kullanabilirsin.
> 
> [OptiScaler.v0.6.2-pre5.zip](https://github.com/user-attachments/files/16072042/OptiScaler.v0.6.2-pre5.zip)
> 
> > Yine olmadı abi. -1.3 yaptı bu sefer. Neyse her türlü çözünürlük değişimi gerekiyorsa kendim elle ayarlarım. Ben oyun başlarken kendisi yapar diye düşünmüştüm.

Abi teşekkür ederim güncelleme için. Sürekli deneme şansım olmadı fakat bilgi almak için soru sorabiliyorsak eğer nasıl bir hesaplama yapmalıyım bilemedim. Önceki sürümde bir hesaplayıcı vardı sanırım onu kaldırmışsın. Netten bulabildiğim kadarıyla bir tek FSR'ın githubında `mipBias = log2(renderResolution/displayResolution) - 1.0;` formülünü bulabildim. Ben normalde 1440p'de oynuyorum. 1.5x Supersample ile 4k'ya çıkarıyorum. 1.0 ratio DLAA/XESS kullanıyorum. Şimdi bu hesaba göre -0.415 çıkıyor gibi. Senin eklemiş olduğunda 0.58 küsür bir şey çıkıyordu. Bunun için nasıl bir hesaplama yapabilirim ve materyal okuyabilirim? Teşekkür ederim.

**Comment by cdozdil** [comment]
Selam,

Biraz gelişmiş ve sorun çıkarabilecek ayarları `Advanced Settings` arkasına aldım. Mipmap hesabı için Intel dokümanlarındaki hesaplamayı kullanıyorum.

![image](https://github.com/cdozdil/OptiScaler/assets/35529761/8cf64146-07c3-49f4-8d6c-c951ef456f4a)

Hesaplanan değerin - olması gerekiyor, çok yüksek değerler performans sıkıntı yaratabilir, aklında olsun.

**Comment by Ridianoid** [comment]
![2024-07-03 14_19_03-](https://github.com/cdozdil/OptiScaler/assets/20602186/fbae20fb-fe49-4a55-a0dc-08f7f22ef925)

Anladığım kadarıyla bu değerlerin - verilmesi normalde upscale methodlarında düşük çözünürlüğün daha yüksek çözünürlüğe çıkarıldığındaki bozulması keskinlik gibi bir şey ile önlemek ama ben tam tersini yapıyorum abi. O zaman ne yapmalıyım? Resimde ekledim. Ben mi yanlış yorumluyorum bilemiyorum. Sanırım bu yaptığım XESS anti alasing modu olarak kullan ama çözünürlüğü ratio 1.0 seçtiğim için bir şey yapma demek. üstüne onu da 1.5x ile 2160p olarak kullanıyorum. Texture kalitesi gerçekten değişiyor. Koyduğun calculator bu şekilde hesaplıyor; 

![2024-07-03 14_19_37-](https://github.com/cdozdil/OptiScaler/assets/20602186/2b4c4a0c-5b9a-4b21-a4a9-eecccca24b4c)

Ben yine de - değer mi vermeliyim. Çünkü senin verdiğin calculatorda 1.0 ratio maksimum kabul ediliği için slider ile oynayamıyorum. 3840'ı elimle yazınca böyle bir hesap çıktı. Bu upscale, downscale muhabbeti hangisi önde sonra yapılıyor vs bilemediğim için kafa karıştırıyor biraz da.

**Comment by cdozdil** [comment]
Sen son upscale yapılacak çözünürlüğü yazmalısın ama orada benim atladığım bir konu var (OutputScaling). 
Hesap şu şekilde senin için log2(2560/3840) = -0.585

**Comment by Ridianoid** [comment]
> Sen son upscale yapılacak çözünürlüğü yazmalısın ama orada benim atladığım bir konu var (OutputScaling). Senin durumunda `Render Width` 2560 ve `Display Width` 3840 oluyor. Hesap şu şekilde senin için log2(2560/3840) = -0.585

Tamamdır abi. Çok teşekkür ederim. Böyle sürekli bir şey aklıma takıldıkça yazıyorum. Umarım rahatsız etmiyorumdur. Lütfen öyle bir durum olursa belirt. 

Ellerine kollarına sağlık Internet Download Manager ve yazdığın Optiscaler kadar yaptığı işin sonucundan bu kadar keyif aldığım bir app daha olmadı. AMD'nin VSR'ından daha iyi çalışan app yapmışsın, üstüne bir sürü faktörle de tek tık ile oynamama izin veriyorsun. Ellerine kollarına sağlık. 

Bu app'in daha gideceği yerleri hevesle takip ediyorum. Vallahi senin yüzünden github bookmark ekledim. PC de gün içinde kaç kere kontrol ediyorum. Son release'ini 10 dk içinde beğenmiştim bildirimi geliyorsa görmüşsündür 
![gross-eek](https://github.com/cdozdil/OptiScaler/assets/20602186/d3c172eb-6b41-46d0-b857-ef6595381976)

**Comment by cdozdil** [comment]
Çok sağol desteğin için, yapmayı planladığım diğer konular;
* FSR3.1 upscaler desteği (bunun için kaynak kodlarını bekliyorum)
* XeSS'i Vulkan üzerinde çalıştırmak (Nukem'in son yaptığı Vulkan çalışmalrı sayesinde olabilir gibi)
* Compute Shader ile yaptığım RCAS/Output Scaling'in DirectX 11'e port etmek (bu nispeten daha hızlı olabilecek bir konu)
* DLSS dışında XeSS ve FSR kaynakları ile de upscale yapabilmek (bunun için upscaler backenlerini ciddi elden geçirmem gerekecek)
* Compute Shader ile yaptığım RCAS/Output Scaling'in Vulkan'a port etmek 

0.6.x sürümleri DLSS Enabler ile aramızdaki görev değişikliği yüzünden nispeten zorlu bir sürüm oldu ve hala bazı sıkıntıları temizliyoruz bu konuda.

**Comment by Ridianoid** [comment]
> Çok sağol desteğin için, yapmayı planladığım diğer konular;
> 
>     * FSR3.1 upscaler desteği (bunun için kaynak kodlarını bekliyorum)
> 
>     * XeSS'i Vulkan üzerinde çalıştırmak (Nukem'in son yaptığı Vulkan çalışmalrı sayesinde olabilir gibi)
> 
>     * Compute Shader ile yaptığım RCAS/Output Scaling'in DirectX 11'e port etmek (bu nispeten daha hızlı olabilecek bir konu)
> 
>     * DLSS dışında XeSS ve FSR kaynakları ile de upscale yapabilmek (bunun için upscaler backenlerini ciddi elden geçirmem gerekecek)
> 
>     * Compute Shader ile yaptığım RCAS/Output Scaling'in Vulkan'a port etmek
> 
> 
> 0.6.x sürümleri DLSS Enabler ile aramızdaki görev değişikliği yüzünden nispeten zorlu bir sürüm oldu ve hala bazı sıkıntıları temizliyoruz bu konuda.

Ben bu mesajı nasıl gözden kaçırmışım. Ellerine sağlık abi. İnşallah ben de senin gibi yazılımcı olabilirim. Çok imrendim :D Tam da sevdiğim sektörle alakalı işler yapıyorsun. Hayali bile çok güzel. Hele bir de yaptığın tıkır tıkır çalışınca verdiği dopamini hayal bile edemiyorum. 

Ben buraya neden geldim? Tabii ki sorun mu emin olamadığım ama bildirmek istediğim bir test sonucu için. Nixxess'in tüm oyunlarına `FSR 3.1` ve her upscale ile çalışabilen `FSR Frame Generation` eklendi biliyorsun. 

Sorun Özeti; `FSR Frame Generation` oyun menüsünde aktifken `Ins` butonu ile arayüzü açamıyorum hata veriyor; 

![2024-07-10 14_04_06-Spider-Man Remastered · Issue #9 · cdozdil_OptiScaler — Mercury](https://github.com/cdozdil/OptiScaler/assets/20602186/714f782b-8194-499e-ace6-de09f0ae0897)

Arayüzü açamasam da oyun içinde DLSS seçtiğim gibi Optiscaler çalışmaya başlıyor. Bir hata vermiyor o şekilde yapınca sadece arayüzü açamıyorum.

**Comment by cdozdil** [comment]
Menu için 3.1 kontrollerini henüz eklemedim, ini'den OverlayMenu=false yaparsan şimdilik işini görecektir.

**Comment by Ridianoid** [comment]
> Menu için 3.1 kontrollerini henüz eklemedim, ini'den OverlayMenu=false yaparsan şimdilik işini görecektir.

Tamamdır abi. Kolay gelsin

**Comment by Ridianoid** [comment]
Abi eski pre'leri nasıl indirebiliyoruz? Pre_6 da sanki output scaling çalışıyordu. pre_7 de hogwarts legacy çözünürlük katlayamıyorum. 2k da kaldım. Tıklanamaz hale geliyor. rar'ı silmişim.

**Comment by cdozdil** [comment]
Selam,

Baktım pre6 ben de yedeklememişim ama pre5 var, belki işine yarar diye paylaşıyorum.

[OptiScaler.v0.6.5-pre5.zip](https://github.com/user-attachments/files/16353280/OptiScaler.v0.6.5-pre5.zip)

**Comment by Ridianoid** [comment]
![2024-07-23 23_53_14-Window](https://github.com/user-attachments/assets/63f1cad8-4704-49ad-8d41-d05f108b8bdc)
![2024-07-23 23_58_41-Window](https://github.com/user-attachments/assets/371b65d6-cf50-4fd9-802c-9074aba6dbc4)
![2024-07-23 23_56_11-Window](https://github.com/user-attachments/assets/d277d72f-a78c-4ac1-a416-bb8f3acf49d0)

Abi yanlış yaptığım bir şey mi var output scaling pre'ler ile kapanmış görünüyor. Neyi gözden kaçırıyorum?

**Comment by cdozdil** [comment]
Selam,

Ekran görüntülerine göre oyun şu anda Display Res. MV kullanıyor, büyük ihtimalle patch vb. ile birşeyler değişmiş. Oyunun `Engine.ini` dosyasına aşağıdaki satırları eklersen büyük ihtimalle sorun düzelecektir.

```ini
[SystemSettings]
r.NGX.DLSS.DilateMotionVectors=0
```

**Comment by Ridianoid** [comment]
> Selam,
> 
> Ekran görüntülerine göre oyun şu anda Display Res. MV kullanıyor, büyük ihtimalle patch vb. ile birşeyler değişmiş. Oyunun `Engine.ini` dosyasına aşağıdaki satırları eklersen büyük ihtimalle sorun düzelecektir.
> 
> ```ini
> [SystemSettings]
> r.NGX.DLSS.DilateMotionVectors=0
> ```

İşe yaramadı abi. Dediğin gibi güncellemeler geldi ama XESS, DLSS vs güncellediler. Gerisi fix olarak geldi. En güncel oyun sürümünde kararlı sürüm olan 0.6.1'de sorunsuz scale edebilirken pre sürümlerde output scaling maalesef kapanıyor. Bunun için herhangi bir log açıp yapıp göndermem gerekiyorsa yardımcı olmak isterim abi.

**Comment by Ridianoid** [comment]
![2024-08-05 01_31_07-Greenshot](https://github.com/user-attachments/assets/973fba0a-5484-48e3-b9b2-d2198ce5865d)
![2024-08-05 01_31_00-Greenshot](https://github.com/user-attachments/assets/ba5c1c20-0ae0-4d53-a949-f675968ba9ac)

abi output scaling 0.6.6 pre sürümde değişmiş sanırım açıklamada da yazıyor ama ekrana sığdırmadan büyütmeye başladı. Bunun için bir çözüm var mı? Menü sabit kalırken oyun görüntüsü büyüyor.

**Comment by Ridianoid** [comment]
> Selam,
> 
> Bu versyonu dener misin? DLAA'da gözdem kaçırdığım bir konu vardı, onu düzelttim.
> 
> [#34 (comment)](https://github.com/cdozdil/OptiScaler/issues/34#issuecomment-2267403107)

Oldu abi. Çok teşekkürler.

**Comment by Ridianoid** [comment]
![2024-08-07 13_20_24-Greenshot](https://github.com/user-attachments/assets/f43d3cd0-f746-4714-8168-fda84aa4b880)
![2024-08-07 13_20_00-Greenshot](https://github.com/user-attachments/assets/679e47a4-1f86-4fce-a0bf-9ef7af0bf95f)

Abi merhabalar. `Mipmap Bias` çözünürlük değiştirsem de, `save ini` yapıp yeniden oyuna girsem de `Current; 0.0000` olarak hesaplanıyor. Bildirmek istedim. `Ratio Override` yüzünden olabilir gibi geldi bana.

**Comment by cdozdil** [comment]
Selam,

DLSS preset değiştirmeyi de dener misin bazen o de işe yarıyor. Açılışta ini ayarının etkili olması için dxgi.dll, version.dll vb. şekilde çalışması gerekiyor. 

Biraz önce DRG ile denedim sorun yoktu, belki oyun ile alakalı da olabilir.

**Comment by Ridianoid** [comment]
> Selam,
> 
> DLSS preset değiştirmeyi de dener misin bazen o de işe yarıyor. Açılışta ini ayarının etkili olması için dxgi.dll, version.dll vb. şekilde çalışması gerekiyor.
> 
> Biraz önce DRG ile denedim sorun yoktu, belki oyun ile alakalı da olabilir.

![2024-08-07 14_42_11-Greenshot](https://github.com/user-attachments/assets/ef407764-2143-429e-9478-43bc37d337fe)

Ben hiç uğraşmayıp her oyunu DLAA seviyesinde oynadığım için override yapıyordum ama presetleri editledim. Bu sefer Quality-Balanced yapınca düzeldi. Teşekkürler.

**Comment by Ridianoid** [comment]
![2024-08-12 20_51_02-x64](https://github.com/user-attachments/assets/37b95400-4853-4e80-a3b5-129bc1a6a99b)

abi merhabalar yine ben. Dying Light 2 Stay Human oyununda DLSS olduğu halde bende DLSS seçeneği gelmiyor. Yapmadığım şey kalmadı. Gözden neyi kaçırıyor olabilirim sence? Tenoke crack kullanıyorum 1.72

**Comment by cdozdil** [comment]
Selam,

Opti'yi [dxgi olarak](https://github.com/cdozdil/OptiScaler?tab=readme-ov-file#install-as-non-nvngx) kurup [nvapi-dummy atmayı](https://github.com/cdozdil/OptiScaler/blob/master/Spoofing.md#usage-2) dener misin?

**Comment by Ridianoid** [comment]
> Selam,
> 
> Opti'yi [dxgi olarak](https://github.com/cdozdil/OptiScaler?tab=readme-ov-file#install-as-non-nvngx) kurup [nvapi-dummy](https://github.com/FakeMichau/nvapi-dummy/releases) atıp [nvngx.ini ile](https://github.com/cdozdil/OptiScaler/blob/master/Spoofing.md#usage-2) yükletmeyi dener misin?

abi harikasın. DLSS geldi ve menüyü açabildim fakat şöyle bir sorun var ki optiscaler menüsüne fare ile kontrol edemiyorum. Klavyede yön tuşları ile hareket edebiliyorum. Onu da feedback vereyim dedim. Yukarıda sana yazdıktan sonra DLSS enabler deneyeyim demiştim. Onda da aynı sorun vardı. Herhalde o da bu şekilde aşıyor.

**Comment by cdozdil** [comment]
Evet Enabler yanında nvapi standart olarak geliyor, zaten DL2 Artur'un sahip olduğu ve deneyebildiği nadir oyunlardan 😊

**Comment by Ridianoid** [comment]
Abi ortalıkta 0.7.0 pre 5 optiscaler dolanıyor. Burada paylaşmamışsın kime ait o uygulama ?

**Comment by cdozdil** [comment]
Onu Discord'da test icin paylasmistim. Nerede cikti karsina, sasirdim 😊

**Comment by Ridianoid** [comment]
> Onu Discord'da test icin paylasmistim. Nerede cikti karsina, sasirdim 😊

Ya takip ettiğim bir hintli eleman var da. FG aktif etmek için çok şey takip etmeye başlamıştım. Orada görünce dedim birisi milleti fena tokatlamaya çalışıyor herhalde. Baya FG falan eklemişsin. Biraz videodan bakıp bıraktım. Kendim keşfetmek istiyorum çıkınca :D Şimdiden hevesle bekliyorum. Kolaylıklar dilerim :D

**Comment by cdozdil** [comment]
Teşekkürler 👍🏻
