### ISSUE TITLE
Frage generation not working in Alan Wake 2

### ISSUE THREAD

**Issue by benjamimgois** [cdozdil/OptiScaler#96]
Hi ! I was using optiscaler 0.7pre24 in Alan Wake 2 (running on Linux) and it was working fine with FSR 3.1 upscaling and FG. But after the update to the deluxe edition (to play the last DLC)  of the game, the Frame Generation toggle in the Graphics option is grayed out. If i enable it via the overlay menu it makes no effect.

![image](https://github.com/user-attachments/assets/ec59d709-4688-4853-b3f6-5841756e2682)
![nofg](https://github.com/user-attachments/assets/d3b9ca18-e0ff-4bae-88aa-fba0e4f25cf1)
![image](https://github.com/user-attachments/assets/f257f987-9982-47c2-b1bd-c56889365af9)

Arch Linux 
Kernel 6.11
Radeon 7900xtx
mesa-git

Just attach my system logs

[dlss-enabler.log](https://github.com/user-attachments/files/17550383/dlss-enabler.log)
[dlssg_to_fsr3.log](https://github.com/user-attachments/files/17550387/dlssg_to_fsr3.log)

**Comment by Hezakiel** [comment]
Hi, 
For Alan Wake 2 you need DLSS enabler to make the FG option available in game.
Cheers

**Comment by benjamimgois** [comment]
Hi, that worked for me. Thanks
